# Generated by Django 2.0.6 on 2018-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=8000)),
                ('batch_size', models.IntegerField(default=5)),
                ('fps', models.IntegerField(default=10)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=120)),
            ],
        ),
    ]
